# Generated by Django 3.0.8 on 2020-07-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aud', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='vsong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('vid', models.FileField(upload_to='')),
                ('thumb', models.ImageField(upload_to='')),
            ],
        ),
    ]
