# Generated by Django 3.0.8 on 2020-07-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_auto_20200713_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asong',
            old_name='thumb',
            new_name='pic',
        ),
        migrations.AddField(
            model_name='asong',
            name='artist',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
