# Generated by Django 3.0.8 on 2020-07-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_auto_20200713_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='ysong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('artist', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
